version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tennis_scheduler
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tennis_scheduler"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  tennis_scheduler:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db/tennis_scheduler"
      SERVER_ADDR: "0.0.0.0:8080"

volumes:
  db-data:
